repos:
  - repo: local
    hooks:
      - id: maven-checkstyle
        name: Maven Checkstyle
        entry: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle.xml
        language: system
        files: \.java$
        pass_filenames: false
