name: Build, Test, and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package

    - name: Run Unit Tests
      run: mvn test

    - name: Create Tag After Test Success
      if: success()
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        echo "Creating new tag: $TAG_NAME"
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME

  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Changelog
      id: changelog
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        changelog=$(git log $latest_tag..HEAD --pretty=format:"- %s" --abbrev-commit)
        echo "::set-output name=changelog::${changelog}"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.changelog }}
