name: Build and Test Java Expense Tracker

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]  # Add Java versions to test against

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Use the preferred Java distribution
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package

    - name: Run Unit Tests
      run: mvn test
