name: Build, Test, and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java-version: [17]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package

    - name: Run Unit Tests
      run: mvn test

    - name: Create Tag After Test Success
      if: success()
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        echo "Creating new tag: $TAG_NAME"
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag $TAG_NAME
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} $TAG_NAME

  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Changelog
      id: changelog
      run: |
        # Check if there are any existing tags
        if git rev-parse --verify "refs/tags/*" >/dev/null 2>&1; then
          latest_tag=$(git describe --tags --abbrev=0)
          changelog=$(git log $latest_tag..HEAD --pretty=format:"- %s" --abbrev-commit)
          echo "::set-output name=changelog::${changelog}"
        else
          echo "No previous tags found, starting fresh."
          echo "::set-output name=changelog::No changelog available."
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
