name: Release on Tag Creation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        java-version: [17]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package

    - name: Run Unit Tests
      run: mvn test

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Runs only on tag creation

    strategy:
      fail-fast: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Changelog
      id: changelog
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        changelog=$(git log $latest_tag..HEAD --pretty=format:"- %s" --abbrev-commit)
        echo "::set-output name=changelog::${changelog}"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/expense-tracker-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.changelog }}
